global:
  scrape_interval: 5s

scrape_configs:
  - job_name: simulator
    static_configs: [{targets: ["simulator:8000"]}]
  - job_name: ingest
    static_configs: [{targets: ["ingest:8000"]}]
  - job_name: anomaly_detector
    static_configs: [{targets: ["anomaly_detector:8000"]}]
  - job_name: alert_agent
    static_configs: [{targets: ["alert_agent:8000"]}]
  - job_name: api
    static_configs: [{targets: ["api:8000"]}]
